//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 08:20:41 AM EST 
//

package edu.techseekers.xml.binding;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"item" })
@XmlRootElement(name = "Salaries")
public class Salaries {

	@XmlElement(required = true)
	protected List<Salaries.item> item;


	public List<Salaries.item> getItem() {
		if (item == null) {
			item = new ArrayList<Salaries.item>();
		}
		return this.item;
	}

	public void print() {
		for (item itemNode : item) {
			System.out.println("Department: "+itemNode.getDepartment()+"     Everage Salary:"+itemNode.getEverageSalary());
		}
	}
	
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "Department", "EverageSalary"})
	public static class item {

		@XmlElement(required = true)
		protected String Department;
		@XmlElement(required = true)
		protected Double EverageSalary;

		public item() {
			
		}
		
		public item(String Department,Double EverageSalary)
		{
			this.Department=Department;
			this.EverageSalary=EverageSalary;
		}
		
		
		/**
		 * Gets the value of the department property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDepartment() {
			return Department;
		}

		/**
		 * Sets the value of the department property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDepartment(String value) {
			this.Department = value;
		}

		/**
		 * Gets the value of the everage salary property.
		 * 
		 * @return possible object is {@link Double }
		 * 
		 */
		public Double getEverageSalary() {
			return EverageSalary;
		}

		/**
		 * Sets the value of the everage salary property.
		 * 
		 * @param value
		 *            allowed object is {@link Double }
		 * 
		 */
		public void setEverageSalary(Double value) {
			this.EverageSalary = value;
		}

	}

}
